theme: jekyll-theme-slate
title: Lab 01
description: Practice using software tools, Practice terminal or shell commands, Practice keyboard shortcuts and Create your first Node.js server-side JavaScript file
